@startuml
Solution43 o-- WebsiteBuilder

class Solution43 {
-{static} final Scanner in
-final String siteName
-final String author
-final boolean wantsJavaScriptFolder
-final boolean wantsCSSFolder
-{static} String askThenReturnString()
-{static} boolean askThenReturnBoolean()
}

class WebsiteBuilder {
-final Path htmlPath
-final Path pathToWebsite
-final String siteName
-final String authorName
-final boolean wantsJavaScriptFolder
-final boolean wantsCSSFolder
+void buildWebsite()
-{static}void sayCreatedDirectory()
-void makeHTML()
}
@enduml